config/routes.rb
Scavhunt::Application.routes.draw do
  resources :users

  get "hunter/index"
  get "hunter/lauren"

  resources :hunts

  resources :tasks

  resources :destinations do
    get 'check_dest_solve', on: :member
  end

  resources :stages

  get "hunter" => 'hunter/index'

  get ':controller(/:action(/:id))'
  put ':controller(/:action(/:id))'
  post ':controller(/:action(/:id))'
  patch ':controller(/:action(/:id))'
  delete ':controller(/:action(/:id))'

end

app/models/hunt.rb
class Hunt < ActiveRecord::Base
  has_many :stages
end

app/controllers/hunts_controller.rb
class HuntsController < ApplicationController
  before_action :set_hunt, only: [:show, :edit, :update, :destroy]

  # GET /hunts
  # GET /hunts.json
  def index
    @hunts = Hunt.all
  end

  # GET /hunts/1
  # GET /hunts/1.json
  def show
  end

  # GET /hunts/new
  def new
    @hunt = Hunt.new
  end

  # GET /hunts/1/edit
  def edit
  end

  # POST /hunts
  # POST /hunts.json
  def create
    @hunt = Hunt.new(hunt_params)

    respond_to do |format|
      if @hunt.save
        format.html { redirect_to @hunt, notice: 'Hunt was successfully created.' }
        format.json { render action: 'show', status: :created, location: @hunt }
      else
        format.html { render action: 'new' }
        format.json { render json: @hunt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hunts/1
  # PATCH/PUT /hunts/1.json
  def update
    respond_to do |format|
      if @hunt.update(hunt_params)
        format.html { redirect_to @hunt, notice: 'Hunt was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @hunt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hunts/1
  # DELETE /hunts/1.json
  def destroy
    @hunt.destroy
    respond_to do |format|
      format.html { redirect_to hunts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hunt
      @hunt = Hunt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hunt_params
      params.require(:hunt).permit(:title, :img_url, :url, :password)
    end
end

app/helpers/hunts_helper.rb
module HuntsHelper
end

app/views/hunts/_form.html.erb
<%= form_for(@hunt) do |f| %>
  <% if @hunt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hunt.errors.count, "error") %> prohibited this hunt from being saved:</h2>

      <ul>
      <% @hunt.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :img_url %><br>
    <%= f.text_field :img_url %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hunts/edit.html.erb
<h1>Editing hunt</h1>

<%= render 'form' %>

<%= link_to 'Show', @hunt %> |
<%= link_to 'Back', hunts_path %>

app/views/hunts/index.html.erb
<h1>Listing hunts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Img url</th>
      <th>Url</th>
      <th>Password</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @hunts.each do |hunt| %>
      <tr>
        <td><%= hunt.title %></td>
        <td><%= hunt.img_url %></td>
        <td><%= hunt.url %></td>
        <td><%= hunt.password %></td>
        <td><%= link_to 'Show', hunt %></td>
        <td><%= link_to 'Edit', edit_hunt_path(hunt) %></td>
        <td><%= link_to 'Destroy', hunt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hunt', new_hunt_path %>

app/views/hunts/new.html.erb
<h1>New hunt</h1>

<%= render 'form' %>

<%= link_to 'Back', hunts_path %>

app/views/hunts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @hunt.title %>
</p>

<p>
  <strong>Img url:</strong>
  <%= @hunt.img_url %>
</p>

<p>
  <strong>Url:</strong>
  <%= @hunt.url %>
</p>

<p>
  <strong>Password:</strong>
  <%= @hunt.password %>
</p>

<%= link_to 'Edit', edit_hunt_path(@hunt) %> |
<%= link_to 'Back', hunts_path %>