config/routes.rb
Scavhunt::Application.routes.draw do
  resources :users

  get "hunter/index"
  get "hunter/lauren"

  resources :hunts

  resources :tasks

  resources :destinations do
    get 'check_dest_solve', on: :member
  end

  resources :stages

  get "hunter" => 'hunter/index'

  get ':controller(/:action(/:id))'
  put ':controller(/:action(/:id))'
  post ':controller(/:action(/:id))'
  patch ':controller(/:action(/:id))'
  delete ':controller(/:action(/:id))'

end

app/models/stage.rb
class Stage < ActiveRecord::Base
  belongs_to :hunt
  has_many :tasks
  has_one :destination

  accepts_nested_attributes_for :destination
  accepts_nested_attributes_for :tasks

  scope :full, -> {joins(:destination)}

  def full
    self.joins(:destination, :tasks)
  end

  def get_dests
    self.joins(:destination)
  end
  def check_complete
    #TODO: refactor to check total points vs total accumulated
    points = Task.where("status = true").sum(:points)
    min_points = Stage.where("stage_order <= "+self.stage_order.to_s).sum(:min_points) 

    if self.destination.status && points >= min_points
      self.status = true
      self.save
      true
    else
      false
    end
  end
end

app/controllers/stages_controller.rb
class StagesController < ApplicationController
  before_action :set_stage, only: [:show, :edit, :update, :destroy]

  # GET /stages
  # GET /stages.json
  def index
    @stages = Stage.all
  end

  # GET /stages/1
  # GET /stages/1.json
  def show
  end

  # GET /stages/new
  def new
    @stage = Stage.new
  end

  # GET /stages/1/edit
  def edit
  end

  # POST /stages
  # POST /stages.json
  def create
    @stage = Stage.new(stage_params)

    respond_to do |format|
      if @stage.save
        format.html { redirect_to @stage, notice: 'Stage was successfully created.' }
        format.json { render action: 'show', status: :created, location: @stage }
      else
        format.html { render action: 'new' }
        format.json { render json: @stage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stages/1
  # PATCH/PUT /stages/1.json
  def update
    respond_to do |format|
      if @stage.update(stage_params)
        format.html { redirect_to @stage, notice: 'Stage was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @stage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stages/1
  # DELETE /stages/1.json
  def destroy
    @stage.destroy
    respond_to do |format|
      format.html { redirect_to stages_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stage
      @stage = Stage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stage_params
      params.require(:stage).permit(:description, :text, :img_url, :status, :min_points, :hunt_id)
    end
end

app/helpers/stages_helper.rb
module StagesHelper
end

app/views/stages/_form.html.erb
<%= form_for(@stage) do |f| %>
  <% if @stage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stage.errors.count, "error") %> prohibited this stage from being saved:</h2>

      <ul>
      <% @stage.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :img_url %><br>
    <%= f.text_field :img_url %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.check_box :status %>
  </div>
  <div class="field">
    <%= f.label :min_points %><br>
    <%= f.number_field :min_points %>
  </div>
  <div class="field">
    <%= f.label :hunt_id %><br>
    <%= f.text_field :hunt_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stages/edit.html.erb
<h1>Editing stage</h1>

<%= render 'form' %>

<%= link_to 'Show', @stage %> |
<%= link_to 'Back', stages_path %>

app/views/stages/index.html.erb
<h1>Listing stages</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Text</th>
      <th>Img url</th>
      <th>Status</th>
      <th>Min points</th>
      <th>Hunt</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @stages.each do |stage| %>
      <tr>
        <td><%= stage.description %></td>
        <td><%= stage.text %></td>
        <td><%= stage.img_url %></td>
        <td><%= stage.status %></td>
        <td><%= stage.min_points %></td>
        <td><%= stage.hunt %></td>
        <td><%= link_to 'Show', stage %></td>
        <td><%= link_to 'Edit', edit_stage_path(stage) %></td>
        <td><%= link_to 'Destroy', stage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stage', new_stage_path %>

app/views/stages/new.html.erb
<h1>New stage</h1>

<%= render 'form' %>

<%= link_to 'Back', stages_path %>

app/views/stages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @stage.description %>
</p>

<p>
  <strong>Text:</strong>
  <%= @stage.text %>
</p>

<p>
  <strong>Img url:</strong>
  <%= @stage.img_url %>
</p>

<p>
  <strong>Status:</strong>
  <%= @stage.status %>
</p>

<p>
  <strong>Min points:</strong>
  <%= @stage.min_points %>
</p>

<p>
  <strong>Hunt:</strong>
  <%= @stage.hunt %>
</p>

<%= link_to 'Edit', edit_stage_path(@stage) %> |
<%= link_to 'Back', stages_path %>